// Generated by ts-to-zod
import { z } from "zod";

export const cardDtoSchema = z.object({
  id: z.number(),
  position: z.number(),
  description: z.string().optional().nullable(),
  text: z.string().optional().nullable(),
});

export const createCardRequestDtoSchema = z.object({
  body: z.object({
    listId: z.number(),
    text: z.string().optional(),
    description: z.string().optional(),
    position: z.number().optional(),
  }),
});

export const createCardResponseDtoSchema = z.object({
  card: cardDtoSchema,
});

export const getCardRequestDtoSchema = z.object({
  pathParams: z.object({
    id: z.string(),
  }),
});

export const getCardResponseDtoSchema = z.object({
  card: cardDtoSchema,
});

export const updateCardRequestDtoSchema = z.object({
  pathParams: z.object({
    id: z.string(),
  }),
  body: z.object({
    listId: z.number().optional(),
    text: z.string().optional(),
    description: z.string().optional(),
    position: z.number().optional(),
  }),
});

export const updateCardResponseDtoSchema = z.object({
  card: cardDtoSchema,
});

export const deleteCardRequestDtoSchema = z.object({
  pathParams: z.object({
    id: z.string(),
  }),
  body: z.object({
    listId: z.number().optional(),
    text: z.string().optional(),
    description: z.string().optional(),
    position: z.number().optional(),
  }),
});

export const deleteCardResponseDtoSchema = z.object({
  success: z.boolean(),
});

export const listDtoSchema = z.object({
  id: z.number(),
  position: z.number(),
  cards: z.array(cardDtoSchema),
  name: z.string().optional().nullable(),
});

export const boardDtoSchema = z.object({
  id: z.number(),
  name: z.string(),
  lists: z.array(listDtoSchema),
});

export const getBoardRequestDtoSchema = z.object({
  pathParams: z.object({
    id: z.string(),
  }),
});

export const getBoardResponseDtoSchema = z.object({
  board: boardDtoSchema,
});

export const updateBoardRequestDtoSchema = z.object({
  pathParams: z.object({
    id: z.string(),
  }),
  body: z.object({
    name: z.string().optional(),
  }),
});

export const updateBoardResponseDtoSchema = z.object({
  board: boardDtoSchema,
});
